# Background and foreground colors
background = #040A00
foreground = #DBC118

# Standard colors
palette = 0=#040A00
palette = 1=#BB8B80
palette = 2=#60834e
palette = 3=#807b00
palette = 4=#A9717B
palette = 5=#b8667a
palette = 6=#5d8448
palette = 7=#DBC118

# Bright colors
palette = 8=#5c5f59
palette = 9=#e6afa0
palette = 10=#80aa62
palette = 11=#a4a100
palette = 12=#d493a0
palette = 13=#e5869f
palette = 14=#7cab59
palette = 15=#f0cf00
