$color = rgba(4, 10, 0, 1)
$inner_color = rgba(4, 10, 0, 0.66)
$outer_color = rgba(184, 102, 122, 1)
$font_color = rgba(219, 193, 24, 1)
$placeholder_color = rgba(219, 193, 24, 0.7)
$check_color = rgba(93, 132, 72, 1)
